Create table CIRCUITS as
SELECT CIRCUITID, NAME, LOCATION, COUNTRY
FROM PLAYGROUND.DATATHON.CIRCUITS;

Create table DRIVERS as
SELECT DRIVERID, FORENAME, SURNAME, DOB
FROM PLAYGROUND.DATATHON.DRIVERS;

Create table RACES as
SELECT RACEID, YEAR, ROUND, CIRCUITID, DATE, NAME
FROM PLAYGROUND.DATATHON.RACES;

Create table CONSTRUCTORS as
SELECT CONSTRUCTORID, NAME
FROM PLAYGROUND.DATATHON.CONSTRUCTORS;

Create table LAP_TIMES as
SELECT RACEID,DRIVERID,LAP,POSITION,MILLISECONDS, 
FROM PLAYGROUND.DATATHON.LAP_TIMES;

Create table SPRINT_RESULTS as
SELECT RACEID, DRIVERID, CONSTRUCTORID, GRID, POSITION, POINTS, LAPS, FASTESTLAP, STATUSID
FROM PLAYGROUND.DATATHON.SPRINT_RESULTS;

Create table STATUS as
SELECT STATUSID, STATUS
FROM PLAYGROUND.DATATHON.STATUS;

Create table PIT_STOPS as
SELECT RACEID, DRIVERID, STOP, LAP, DURATION,MILLISECONDS
FROM PLAYGROUND.DATATHON.PIT_STOPS;

Create table QUALIFYING as
SELECT DRIVERID,RACEID,Q1,Q2,Q3,
FROM PLAYGROUND.DATATHON.QUALIFYING;

Create table RESULTS as
SELECT RACEID,DRIVERID,CONSTRUCTORID,GRID,POSITION,POINTS,LAPS,FASTESTLAP,STATUSID
FROM PLAYGROUND.DATATHON.RESULTS;

Create table DRIVER_STANDINGS as
SELECT RACEID, DRIVERID, POINTS, POSITION
FROM PLAYGROUND.DATATHON.DRIVER_STANDINGS;

Create table CONSTRUCTOR_STANDINGS as
SELECT CONSTRUCTORSTANDINGSID, RACEID, CONSTRUCTORID, POINTS, POSITION, WINS
FROM PLAYGROUND.DATATHON.CONSTRUCTOR_STANDINGS;
